[package]
name = "leptoaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-timers = { version = "0.3.0", features = ["futures"] }
leptos = { version = "0.6.5", features = ["csr", "nightly"] }
