[package]
name = "leptoaster"
version = "0.1.8"
edition = "2021"
license = "MIT"
description = "A minimal toast library for Leptos."
repository = "https://github.com/KiaShakiba/leptoaster"
readme = "README.md"
keywords = ["leptos", "toast", "web", "ui", "userinterface"]
categories = ["gui", "web-programming"]

[dependencies]
gloo-timers = { version = "0.3", features = ["futures"] }
leptos = { version = "0.6", features = ["csr"] }
